### ISSUE TITLE
As an admin, I want to create frameworks which contains a main competencies, so I can quickly navigate through the competencies.

### ISSUE THREAD

**Issue by alexandervFS** [OpenSkool/OpenSkool#109] opened 2022-03-28 11:36 UTC
## UAT

Given none of the framework contains the name of the new framework,
When I add a new framework
Then the framework gets added

 Given a framework exists with the name of the new framework
When I try to add the framework with an existing name
Then I get an error message that a framework already exists with the same name

![image](https://user-images.githubusercontent.com/100140906/160391208-9d523f0d-7cee-4681-a70f-10f7cbf48717.png)

## To Do

- [x] BE: Add CompetencyFramework domain model
  - [x] Link CompetencyFramework to RootCompetency
  - [x] List CompetencyFramework
  - [x] Get CompetencyFramework by id
    - [x] Add API integration tests
  - [X] Add Create CompetencyFramework
    - [x] Validate duplicate title
    - [x] Add API integration tests
  - [x] Competency should always have competencyFramework
- [x] BE: Add Framework arg to CreateCompetency mutation
- [x] FE: Update FE
  - [x] Restructure routes
    - [x] `/manage/frameworks` list CompetencyFramework
    - [x] `/manage/frameworks/create-framework` create CompetencyFramework
    - [x] `/manage/frameworks/:framework-id` list RootCompetency of CompetencyFramework
    - [x] `/manage/frameworks/:framework-id/create-competency` create RootCompetency in CompetencyFramework
    - [x] `/manage/frameworks/:framework-id/:competency-id` list NestedCompetency of RootCompetency
    - [x] `/manage/frameworks/:framework-id/:competency-id/create-competency` create NestedCompetency in NestedCompetency
    - [x] `/manage/frameworks/:framework-id/:competency-id/edit` edit Competency

**Comment by SiteSeerBE** [comment] 2022-04-19 12:25
Do we edit and delete frameworks?

**Comment by shkurata** [comment] 2022-04-26 15:51
All task are done!

**Comment by Moeriki** [comment] 2022-04-27 09:35
I get an error when creating a framework.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/38758/165489085-ab5edcad-6216-40a5-b48a-2bdfcbec4b53.png">

**Comment by SiteSeerBE** [comment] 2022-04-27 09:39
> I get an error when creating a framework.

Can't reproduce locally or on dev.

**Comment by SiteSeerBE** [comment] 2022-04-27 09:49
Can't reproduce after sign-in, but noticed the same problem with "create competency" eventually. I'm under the impression that when you wait a while you get an "unauthorized" response from the gql call. Trying to reproduce once more.

**Comment by Moeriki** [comment] 2022-04-27 09:51
After deploy it was also fixed for me. It's not an issue with this ticket but with the auth setup.

I will close this again and track further findings in auth ticket.

**Closed by Moeriki** 2022-04-27 09:51 UTC
Labels: type:story
